name: Build and Publish Image to ghcr
on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    name: Build and publish image
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: kargo-demo-app
        tags: latest ${{ github.ref_name }}
        containerfiles: |
          ./Dockerfile

    - name: Publish To ghcr.io
      id: publish-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/christianh814
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image published as ${{ steps.push-to-ghcr.outputs.registry-paths }}"
